# Generated by Django 3.0.7 on 2020-09-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
