# Generated by Django 3.0.7 on 2020-09-22 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DR', 'Deleware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('website_url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('AG', 'Aging'), ('AF', 'Agriculture and Food'), ('AC', 'Arts and Culture'), ('AS', 'Athletics and Sports'), ('CY', 'Children and Youth'), ('CS', 'Civil Society'), ('CE', 'Community and Economic Development'), ('CT', 'Computers and Technology'), ('CP', 'Consumer Protection'), ('CR', 'Crime and Safety'), ('DI', 'Disabilities'), ('DO', 'Domestic Violence Prevention'), ('EL', 'Education and Literacy'), ('EM', 'Employment and Labor'), ('EE', 'Energy and Environment'), ('LI', 'LGBTQI'), ('GR', 'Government Reform'), ('HW', 'Health and Wellness'), ('HO', 'Housing and Homelessness'), ('HR', 'Human Rights and Civil Liberties'), ('HU', 'Hunger'), ('IM', 'Immigration'), ('JM', 'Journalism and Media'), ('MB', 'Men and Boys'), ('NP', 'Nonprofits and Philanthropy'), ('PF', 'Parenting and Families'), ('PO', 'Poverty'), ('PJ', 'Prison and Judicial Reform'), ('RE', 'Race and Ethnicity'), ('RI', 'Religion'), ('SC', 'Science'), ('SA', 'Substance Abuse and Recovery'), ('TR', 'Transportation'), ('WE', 'Welfare and Public Assistance'), ('WG', 'Woman and Girls')], max_length=2)),
                ('ein', models.CharField(max_length=15)),
                ('fiscal_sponsor', models.CharField(max_length=200)),
                ('guidestar_url', models.CharField(max_length=200)),
                ('logo_url', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('mission_statements', models.TextField(max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=256)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization')),
            ],
        ),
    ]
