# Generated by Django 3.0.7 on 2020-09-22 01:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Org. Contact Phone', max_length=31),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
