# Generated by Django 3.0.7 on 2020-09-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200922_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary',
            new_name='Gallery',
        ),
    ]
