# Generated by Django 3.0.7 on 2020-09-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200922_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardMembers',
            new_name='BoardMember',
        ),
    ]
