# Generated by Django 3.0.7 on 2020-09-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200922_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.CharField(default='https://www.resetyourbody.com/wp-content/uploads/COMPANY_LOGO/logo-default.png', max_length=200),
        ),
    ]
