# Generated by Django 3.0.7 on 2020-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200923_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='mission_statements',
        ),
        migrations.AddField(
            model_name='organization',
            name='mission_statement',
            field=models.TextField(default='', max_length=500, verbose_name='mission statement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(max_length=500, verbose_name='about us'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fiscal_sponsor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='guidestar_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
