# Generated by Django 2.2.12 on 2020-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200923_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='company',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmember',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
